# Generated by Django 6.1 on 2026-09-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='excerpt',
            field=models.CharField(max_length=300),
        ),
    ]
